spring.profiles.active=local

server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=poa123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=poa-ssl-key

#Mongo
spring.data.mongodb.uri=mongodb://host.docker.internal:27017/test

#Logging
logging.level.org.mongodb.driver=ERROR
logging.level.org.springframework.web=ERROR

# Prometheus Metrics
management.endpoints.web.exposure.include: prometheus, health, info
management.endpoints.prometheus.enabled: true